"""Initial schema setup

Revision ID: fd4d82893d91
Revises: 
Create Date: 2026-07-04 15:04:07.498489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd4d82893d91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('HR', 'EMPLOYEE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_company_email'), 'user', ['company_email'], unique=True)
    op.create_table('accesswhitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allowed_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_role', sa.Enum('HR', 'EMPLOYEE', name='userrole'), nullable=False),
    sa.Column('created_by_hr_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_hr_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accesswhitelist_allowed_email'), 'accesswhitelist', ['allowed_email'], unique=True)
    op.create_table('alertlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('TAMPER_DETECTED', 'FILE_UPLOADED', 'TASK_LOGGED', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertlog_alert_type'), 'alertlog', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alertlog_resolved'), 'alertlog', ['resolved'], unique=False)
    op.create_index(op.f('ix_alertlog_severity'), 'alertlog', ['severity'], unique=False)
    op.create_index(op.f('ix_alertlog_timestamp'), 'alertlog', ['timestamp'], unique=False)
    op.create_index(op.f('ix_alertlog_user_id'), 'alertlog', ['user_id'], unique=False)
    op.create_table('chatmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('direction', sa.Enum('OUTBOUND', 'INBOUND', name='messagedirection'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('google_message_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_direction'), 'chatmessage', ['direction'], unique=False)
    op.create_index(op.f('ix_chatmessage_google_message_name'), 'chatmessage', ['google_message_name'], unique=True)
    op.create_index(op.f('ix_chatmessage_space_id'), 'chatmessage', ['space_id'], unique=False)
    op.create_index(op.f('ix_chatmessage_timestamp'), 'chatmessage', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chatmessage_user_id'), 'chatmessage', ['user_id'], unique=False)
    op.create_table('filelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('google_drive_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('drive_folder_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filelog_google_drive_file_id'), 'filelog', ['google_drive_file_id'], unique=False)
    op.create_index(op.f('ix_filelog_timestamp'), 'filelog', ['timestamp'], unique=False)
    op.create_index(op.f('ix_filelog_user_id'), 'filelog', ['user_id'], unique=False)
    op.create_table('leavewfhrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.Enum('LEAVE', 'WFH', name='requesttype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('employee_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='requeststatus'), nullable=False),
    sa.Column('hr_note', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('reviewed_by_hr_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_hr_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leavewfhrequest_created_at'), 'leavewfhrequest', ['created_at'], unique=False)
    op.create_index(op.f('ix_leavewfhrequest_status'), 'leavewfhrequest', ['status'], unique=False)
    op.create_index(op.f('ix_leavewfhrequest_user_id'), 'leavewfhrequest', ['user_id'], unique=False)
    op.create_table('meetlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('meet_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_space_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetlog_creator_id'), 'meetlog', ['creator_id'], unique=False)
    op.create_index(op.f('ix_meetlog_timestamp'), 'meetlog', ['timestamp'], unique=False)
    op.create_table('tasklog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('hmac_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_sheet_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasklog_timestamp'), 'tasklog', ['timestamp'], unique=False)
    op.create_index(op.f('ix_tasklog_user_id'), 'tasklog', ['user_id'], unique=False)
    op.create_table('timelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=False),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timelog')
    op.drop_index(op.f('ix_tasklog_user_id'), table_name='tasklog')
    op.drop_index(op.f('ix_tasklog_timestamp'), table_name='tasklog')
    op.drop_table('tasklog')
    op.drop_index(op.f('ix_meetlog_timestamp'), table_name='meetlog')
    op.drop_index(op.f('ix_meetlog_creator_id'), table_name='meetlog')
    op.drop_table('meetlog')
    op.drop_index(op.f('ix_leavewfhrequest_user_id'), table_name='leavewfhrequest')
    op.drop_index(op.f('ix_leavewfhrequest_status'), table_name='leavewfhrequest')
    op.drop_index(op.f('ix_leavewfhrequest_created_at'), table_name='leavewfhrequest')
    op.drop_table('leavewfhrequest')
    op.drop_index(op.f('ix_filelog_user_id'), table_name='filelog')
    op.drop_index(op.f('ix_filelog_timestamp'), table_name='filelog')
    op.drop_index(op.f('ix_filelog_google_drive_file_id'), table_name='filelog')
    op.drop_table('filelog')
    op.drop_index(op.f('ix_chatmessage_user_id'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_timestamp'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_space_id'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_google_message_name'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_direction'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_alertlog_user_id'), table_name='alertlog')
    op.drop_index(op.f('ix_alertlog_timestamp'), table_name='alertlog')
    op.drop_index(op.f('ix_alertlog_severity'), table_name='alertlog')
    op.drop_index(op.f('ix_alertlog_resolved'), table_name='alertlog')
    op.drop_index(op.f('ix_alertlog_alert_type'), table_name='alertlog')
    op.drop_table('alertlog')
    op.drop_index(op.f('ix_accesswhitelist_allowed_email'), table_name='accesswhitelist')
    op.drop_table('accesswhitelist')
    op.drop_index(op.f('ix_user_company_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
