from sqlmodel import SQLModel, Field, Relationship
from typing import Optional, TYPE_CHECKING
from datetime import datetime

if TYPE_CHECKING:
    from .user import User


class MeetLog(SQLModel, table=True):
    """
    Stores metadata for every Google Meet link generated by the system.
    """

    __tablename__ = "meetlog"

    id: Optional[int] = Field(default=None, primary_key=True)

    # Foreign key pointing to the creator (User)
    creator_id: int = Field(foreign_key="user.id", index=True, nullable=False)

    # The generated Google Meet URL
    meet_url: str = Field(nullable=False)

    # Optional Google Chat space identifier if the meeting was broadcasted
    target_space_id: Optional[str] = Field(default=None, nullable=True)

    # Meeting topic or summary
    topic: str = Field(default="Instant Sync", nullable=False)

    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        nullable=False,
        index=True,
    )

    # Relationship to user
    creator: Optional["User"] = Relationship(back_populates="meet_logs")
