from sqlmodel import SQLModel, Field, Relationship
from typing import Optional, List, TYPE_CHECKING
from datetime import datetime
from enum import Enum

if TYPE_CHECKING:
    from .tasklog import TaskLog
    from .filelog import FileLog
    from .leavewfhrequest import LeaveWFHRequest
    from .chatmessage import ChatMessage
    from .meetlog import MeetLog
    from .alertlog import AlertLog


class UserRole(str, Enum):
    HR = "hr"
    EMPLOYEE = "employee"


class User(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    company_email: str = Field(unique=True, index=True)
    role: UserRole
    is_active: bool = True
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    # Relationship to access whitelist
    access_whitelist_entries: List["AccessWhitelist"] = Relationship(back_populates="created_by")

    # Relationship to time logs
    time_logs: List["TimeLog"] = Relationship(back_populates="user")

    # Relationship to task logs
    task_logs: List["TaskLog"] = Relationship(back_populates="user")

    # Relationship to file logs
    file_logs: List["FileLog"] = Relationship(back_populates="user")

    # Relationship to leave / WFH requests submitted by this user
    leave_wfh_requests: List["LeaveWFHRequest"] = Relationship(
        back_populates="employee",
        sa_relationship_kwargs={
            "foreign_keys": "[LeaveWFHRequest.user_id]",
            "lazy": "select",
        },
    )

    # Relationship to requests reviewed by this HR user
    reviewed_requests: List["LeaveWFHRequest"] = Relationship(
        back_populates="reviewed_by",
        sa_relationship_kwargs={
            "foreign_keys": "[LeaveWFHRequest.reviewed_by_hr_id]",
            "lazy": "select",
        },
    )

    # Relationship to chat messages
    chat_messages: List["ChatMessage"] = Relationship(back_populates="user")

    # Relationship to Google Meet links generated by this user
    meet_logs: List["MeetLog"] = Relationship(back_populates="creator")

    # Relationship to security and activity alerts involving this user
    alert_logs: List["AlertLog"] = Relationship(back_populates="user")


class AccessWhitelist(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    allowed_email: str = Field(unique=True, index=True)
    assigned_role: UserRole
    created_by_hr_id: int = Field(foreign_key="user.id")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    # Relationship to user
    created_by: "User" = Relationship(back_populates="access_whitelist_entries")