"""
Google Meet Service Client
===========================
Generates live Google Meet links programmatically by creating a short-lived
Google Calendar event with auto-provisioned conference data.

Fallback / Mock mode:
    If GOOGLE_CALENDAR_CREDENTIALS is not configured or the Google API fails,
    returns a mock URL of format 'https://meet.google.com/abc-defg-hij' (with a
    randomised string to simulate distinct rooms) so local development works.
"""

import logging
import os
import uuid
from datetime import datetime, timedelta, timezone
from typing import Optional

from core.config import settings

logger = logging.getLogger(__name__)


class GoogleMeetClient:
    """
    Client for generating Meet links via the Google Calendar API.
    """

    def __init__(self) -> None:
        self.service = None
        self._mock_mode = True

        credentials_path: Optional[str] = settings.GOOGLE_CALENDAR_CREDENTIALS

        # If no dedicated calendar credentials, fallback to other configured credentials
        if not credentials_path:
            credentials_path = (
                settings.GOOGLE_DRIVE_CREDENTIALS or settings.GOOGLE_SHEETS_CREDENTIALS
            )

        if not credentials_path:
            logger.warning(
                "No Google API credentials set. "
                "GoogleMeetClient running in mock/fallback mode."
            )
            return

        if not os.path.isfile(credentials_path):
            logger.warning(
                "Credentials file '%s' not found. "
                "GoogleMeetClient running in mock/fallback mode.",
                credentials_path,
            )
            return

        try:
            from googleapiclient.discovery import build
            from google.oauth2 import service_account

            scopes = ["https://www.googleapis.com/auth/calendar.events"]
            creds = service_account.Credentials.from_service_account_file(
                credentials_path, scopes=scopes
            )
            self.service = build("calendar", "v3", credentials=creds, cache_discovery=False)
            self._mock_mode = False
            logger.info("GoogleMeetClient successfully initialised using Calendar API.")
        except ImportError:
            logger.warning(
                "google-api-python-client is not installed. "
                "GoogleMeetClient running in mock/fallback mode."
            )
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "Failed to initialise GoogleMeetClient: %s. "
                "Running in mock/fallback mode.",
                exc,
            )

    def create_instant_meet_room(self, topic: str) -> str:
        """
        Create a calendar event with a Google Meet conference solution.

        Args:
            topic: The summary / topic of the meeting.

        Returns:
            The live Google Meet URL, or a mock URL fallback.
        """
        # Generate a distinct mock identifier for unique rooms
        unique_suffix = uuid.uuid4().hex[:10]
        # Format: meet.google.com/abc-defg-hij -> three parts of 3, 4, 3 chars
        mock_meet_url = f"https://meet.google.com/{unique_suffix[:3]}-{unique_suffix[3:7]}-{unique_suffix[7:10]}"

        if self._mock_mode or self.service is None:
            logger.warning(
                "[MOCK] Created virtual Google Meet room '%s' -> %s",
                topic,
                mock_meet_url,
            )
            return mock_meet_url

        try:
            now = datetime.now(timezone.utc)
            # Create a 30-minute block for the instant meeting
            start_iso = now.isoformat()
            end_iso = (now + timedelta(minutes=30)).isoformat()

            # Unique request ID to ensure idempotency for Meet creation
            request_id = uuid.uuid4().hex

            event_payload = {
                "summary": topic,
                "description": "Programmatic instant sync generated by HR-Productivity Hub",
                "start": {"dateTime": start_iso, "timeZone": "UTC"},
                "end": {"dateTime": end_iso, "timeZone": "UTC"},
                "conferenceData": {
                    "createRequest": {
                        "requestId": request_id,
                        "conferenceSolutionKey": {"type": "hangoutsMeet"},
                    }
                },
            }

            # Create event with conferenceDataVersion=1 to instruct the Calendar API
            # to provision a Meet link.
            created_event = (
                self.service.events()
                .insert(
                    calendarId="primary",
                    body=event_payload,
                    conferenceDataVersion=1,
                )
                .execute()
            )

            # Extract the generated hangoutLink
            hangout_link: Optional[str] = created_event.get("hangoutLink")
            if hangout_link:
                logger.info(
                    "Google Meet link successfully provisioned: %s",
                    hangout_link,
                )
                return hangout_link

            logger.warning(
                "Calendar event created but no Meet hangoutLink returned. "
                "Using mock fallback."
            )
            return mock_meet_url

        except Exception as exc:  # noqa: BLE001
            logger.error(
                "Failed to provision Google Meet room via Calendar API: %s. "
                "Returning mock link.",
                exc,
            )
            return mock_meet_url


# Module-level singleton
meet_client = GoogleMeetClient()
